version: "3.9"
services:

  mysql-database:
    container_name: mysql-database
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file: ./.env
      
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-database:/var/lib/mysql

  website:
    container_name: website
    image: nginx:alpine
    volumes:
      - ./website/nginx.conf:/etc/nginx/nginx.conf
      - ./website/dist:/usr/share/nginx/html
      - ./website:/var/www/html
    depends_on:
      - login-service
      - products-service
    ports:
      - "80:80"

  
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy-nginx
    depends_on:
      - website
      - login-service
      - products-service
    volumes:
      - ./reverse-proxy:/etc/nginx
    ports:
      - 5000:5000

  login-service:
    container_name: login-service
    restart: unless-stopped
    image: node:15
    working_dir: /home/node/app-login
    env_file: ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./login-service:/home/node/app-login
      - ./login-service/node_modules:/home/node/app-login/node_modules
    ports:
      - "5001:5001"
    command: ["./wait-for-it.sh", "-t", "90", "mysql-database:3306", "--", "npm", "start"]
    depends_on:
      - mysql-database

  products-service:
    container_name: products-service
    restart: unless-stopped
    image: node:15
    working_dir: /home/node/app-products
    env_file: ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./products-service:/home/node/app-products
      - ./products-service/node_modules:/home/node/app-products/node_modules
    ports:
      - "5002:5002"
    command: ["./wait-for-it.sh", "-t", "90", "mysql-database:3306", "--", "npm", "start"]
    depends_on:
      - mysql-database

  python-api:
    container_name: python-api
    build: ./python_service
    volumes:
      - ./python_service:/usr/src/app/python-api
    ports:
      - "5090:5090"

volumes:
  mysql-database:
